import SupabaseProvider from '@/components/providers/supabase-provider';
import SupabaseAuthProvider from '@/components/providers/supabse-auth-provider';
import { createClient } from '@/utils/supabase-server';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const supabase = createClient();

    const { data: { session } = {} } = await supabase.auth.getSession();

    return (
        <html lang="en">
            <body className={inter.className}>
                <SupabaseProvider>
                    <SupabaseAuthProvider serverSession={session}>
                        {children}
                    </SupabaseAuthProvider>
                </SupabaseProvider>
            </body>
        </html>
    );
}
